services:

    # Notifier

    notification_api_client.notifier:
        class: IDCI\Bundle\NotificationApiClientBundle\Service\Notifier
        arguments:
            - '@da_api_client.api.notification'
            - '%notification_api_client.source_name%'
            - '%notification_api_client.notification_types%'
            - '@session'
